### ISSUE TITLE
File Names not being read correctly

### ISSUE THREAD

**Issue by Nicba1010** [AlexAltea/psarc-tool#2]
psarc-tool output
```
5689 15.56 Kb ar-truck-chase-drk-003.xvag
5690 75.11 Kb ar-truck-chase-drk-004.xvag
5691 33.43 Kb ar-truck-chase-drk-005.xvag
5692 32.48 Kb ar-truck-chase-drk-006.xvag
5693 13.15 Kb ar-truck-chase-drk-007.xvag
```
PS-Tools output (my tool)
```
Entry #5689 (15.56 KiB): war-truck-chase-drk-003.xvag
Entry #5690 (75.11 KiB): war-truck-chase-drk-004.xvag
Entry #5691 (33.43 KiB): war-truck-chase-drk-005.xvag
Entry #5692 (32.48 KiB): war-truck-chase-drk-006.xvag
Entry #5693 (13.15 KiB): war-truck-chase-drk-007.xvag
```

**Comment by AlexAltea** [comment]
Does it also happen with the original PSARC tool? Link: https://www.ferb.fr/ps3/PSARC/

**Comment by Nicba1010** [comment]
I could not test it with that tool but I used another one that is mentioned on ps3devwiki to be coming from the leaked SDK and it outputs like mine.
Tool:
http://www.mediafire.com/?o3wy35uublreh

**Comment by AlexAltea** [comment]
Sure, I'm not arguing that that the output of this tool is correct.
The reason we need to test Matthieu Milan's tool is to know whether:
1. The bug was present in the original PSARC tool from Matthieu Milan.
2. The bug was caused by my port of the original PSARC tool.

**Comment by Nicba1010** [comment]
Interesting bug, provided files for comparison.  
First entry is ok, it isn't missing the first character, all the others are missing the first character.  
Matthieu Milan's tool output is correct, the bug was caused by your port of the original PSARC tool.
[english.psarc-alexaltea.txt](https://github.com/AlexAltea/psarc-tool/files/2826101/english.psarc-alexaltea.txt)
[english.psarc-matthieumillan.txt](https://github.com/AlexAltea/psarc-tool/files/2826102/english.psarc-matthieumillan.txt)

**Comment by GingerAdonis** [comment]
I've fixed this issue in my fork (based on this repo): https://github.com/JarnoVgr/psarc-tool

This specific commit fixes this issue: https://github.com/JarnoVgr/psarc-tool/commit/f4a3ba07debcbbc0baa95246e54b671fbde6d897

**Comment by AlexAltea** [comment]
@JarnoVgr Thanks for tracking the bug down! I've applied your patch on top of `master`.

@Nicba1010 Can you test the latest revision, i.e. ad4c0622cdfe531c625cbea80167c627392dda19?

**Comment by Nicba1010** [comment]
Awesome @JarnoVgr !
I can confirm that the bug has indeed been fixed @AlexAltea
